@baseUrl = http://localhost:5000
@urlPath = api/v1

###
POST {{baseUrl}}/{{urlPath}}/post/reaction
Content-Type: application/json
Accept: application/json
withCredentials: true

{
  "userTo": "63a858b3d547cf2d8147595c",
  "postId": "63b6e17d7d0ed746c3287610",
  "type": "sad",
  "previousReaction": "happy",
  "postReactions": {"like": 0,"love": 0,"happy": 0,"wow": 0,"sad": 1,"angry": 0},
  "profilePicture": "https://res.cloudinary.com/alegria/image/upload/v1670685326/6394a28d7a498c4837fbf523.jpg"
}


###
DELETE {{baseUrl}}/{{urlPath}}/post/reaction/
Content-Type: application/json
Accept: application/json
withCredentials: true


###
GET {{baseUrl}}/{{urlPath}}/post/reactions/63b6e17d7d0ed746c3287610
Content-Type: application/json
Accept: application/json
withCredentials: true


###
GET {{baseUrl}}/{{urlPath}}/post/single/reaction/Koki/63b6e17d7d0ed746c3287610
Content-Type: application/json
Accept: application/json
withCredentials: true


###
GET {{baseUrl}}/{{urlPath}}/post/reactions/username/koki
Content-Type: application/json
Accept: application/json
withCredentials: true
